Demonstrates a  test for the the `ID` and `TIMESTAMP` headers propagated to consumers with Spring Cloud Stream Kafka Bindings.

Run the tests with:

[source,console]
----
./mvnw test
----

The test in `DemoApplicationTests` does the following:
. Starts up embedded Kafka with channels bound to consumer groups
. Creates a message using Spring Integration's `MessageBuilder` and asserts that the `TIMESTAMP` and `ID` are there before sending
. Uses the Spring Cloud Stream bindings to send the message to the Kafka broker
. Once the message is consumed by the listener, that is saved off for later assertions
. Assertions are made to demonstrate that the `ID` and `TIMESTAMP` are not there, but a custom header and payload are

https://stackoverflow.com/questions/57974910/why-are-the-timestamp-and-id-headers-from-spring-integration-unmapped-in-spring[Related Stack Overflow issue]

## Resolution

This has been resolved by setting https://cloud.spring.io/spring-cloud-static/spring-cloud-stream-binder-kafka/2.2.1.RELEASE/spring-cloud-stream-binder-kafka.html#kafka-consumer-properties[`spring.cloud.stream.kafka.default.consumer.standard-headers=both`].
